### ISSUE TITLE
LaZagna does not appear to work

### ISSUE THREAD

**Issue by Techbrunch** [Syslifters/offsec-tools#1]
I wanted to test LaZagna to test it on an [HTB machine](https://0xdf.gitlab.io/2022/09/17/htb-streamio.html) and I used your version since the official repo is lagging behind the latest changes but it does not appear to work.

When I run LaZagna there are not output.

```
*Evil-WinRM* PS C:\Users\nikk37\Documents> dir


    Directory: C:\Users\nikk37\Documents


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/18/2023   7:08 PM        6475231 laZagne.exe


*Evil-WinRM* PS C:\Users\nikk37\Documents> .\laZagne.exe
*Evil-WinRM* PS C:\Users\nikk37\Documents> .\laZagne.exe all -v
```

**Comment by cmahrl** [comment]
Thanks for reporting! We‘ll have a look. Maybe some issue with pyinstaller.

**Comment by cmahrl** [comment]
Fixed issue with pyinstaller. Lazagne should work now in the newest release.
