### ISSUE TITLE
Whisker Tool Addition

### ISSUE THREAD

**Issue by frereit** [Syslifters/offsec-tools#5]
[Whisker](https://github.com/eladshamir/Whisker) is a tool to create shadow credentials and I believe it would be a useful addition to this awesome collection.

**Comment by cmahrl** [comment]
Hi, thanks for the suggestion. We will add it.

**Comment by frereit** [comment]
Hey, thanks very much for adding Whisker! It seems like Whisker isn't include in the public [.gitlab-ci.yml](https://github.com/Syslifters/offsec-tools/blob/main/gitlab-ci.yml) yet, though. Are you planning on including this here as well?

**Comment by cmahrl** [comment]
[gitlab-ci.yml](https://github.com/Syslifters/offsec-tools/blob/main/gitlab-ci.yml) has been updated :)
